name: Cron run component tests and show reports

on: 
  workflow_dispatch:

jobs:
  create-docker-build:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/component-tests.yml
    with:
      tagname: test-component-docker-image
      dockerfile: ./Pytest_docker/Dockerfile
      allure_result_folder: allure-results
    secrets: inherit
